version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "automerge"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    versioning-strategy: "increase"
    rebase-strategy: "auto"
    ignore: []  # nếu không ignore gì thì để [] 
